[workspace]
resolver = "2"
members = [
    "erasure-coding",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Mokshesh Dafariya <mokshesh@outlook.com>"]
license = "MIT OR Apache-2.0"

[workspace.dependencies]
# Add common dependencies here that can be shared across experiments
